just check if there is a spec file, if we arent in cpio mode
openSUSE/obs-service-bundle_gems pull request #8
Opened 2018-06-19 11:49 UTC by vpereira

if an user is trying to use the cpio mode, without a spec file, it should work

2018-06-19 12:01 UTC, ChrisBr commented
@vpereira Please add a reason in your commit message
e.g.
> so the service can be used for builds without a specfile e.g. Kiwi

2018-06-19 12:01 UTC, ChrisBr commented
@jordimassaguerpla please review

2018-06-19 12:24 UTC, jordimassaguerpla requested changes
As ChrisBr stated, please add a reason why you want to run the cpio without a spec file.

2018-06-19 12:25 UTC, jordimassaguerpla reviewed
I just realized,  we don't add the cpio in the spec file as a source?

2018-06-19 12:27 UTC, jordimassaguerpla commented
Answering myself to myself: we have a _service file for the cpio :)

2018-06-19 18:22 UTC, vpereira commented
updated the git log. thank you

2018-06-20 08:49 UTC, jordimassaguerpla approved these changes

2018-06-20 08:49 UTC, merged

2018-06-20 08:49 UTC, jordimassaguerpla commented
Thanks @vpereira !